### ISSUE TITLE
What is the suggested way for editing inscatter, irradiance, and transmittance textures?

### ISSUE THREAD

**Issue by StarArawn** [simeonradivoev/GPU-Planetary-Rendering#2]
I know what format the files say they are in the code, but how can I read them into say photoshop to edit? Perhaps dds would be a better file format as it easily supports 3D textures and can be easily edited in photoshop?

**Comment by simeonradivoev** [comment]
The texture was generated using a c++ code I can no longer find. So I'm guessing photoshop is your best option.

**Comment by simeonradivoev** [comment]
Actually come to think of it it might be from there https://github.com/ebruneton/precomputed_atmospheric_scattering
or from some of the other stuff here
http://evasion.inrialpes.fr/~Eric.Bruneton/
