### ISSUE TITLE
Horizon Boundary Artifact

### ISSUE THREAD

**Issue by AustinSmith13** [simeonradivoev/GPU-Planetary-Rendering#3]
I noticed that when you transition from the ground calculations to the look up texture that is the upper sky for both attenuation and inscatter, it fails to detect mountains and uses the lookup texture instead. Do you have any ideas how to go about fixing this, I'm a little bit stumped on a solution.

![bug](https://user-images.githubusercontent.com/8560365/104260943-0d287380-544a-11eb-9bba-c5e05976c932.png)

**Comment by AustinSmith13** [comment]
@simeonradivoev I have a solution to this problem now. I'm not sure if this is the correct way to go about realistic rendering, but works for what I need. I'll explain how I arrived to this solution.

## The Solution
![Attenuation_Broken](https://user-images.githubusercontent.com/8560365/104269075-0a824a00-545b-11eb-9ef8-bb6d8dac6852.PNG)

before we calculated the attenuation if it was below the horizon, the original function for Transmittance handled the bottom and top half of the atmosphere.

I removed the function Transmittance and created a new function called Transmittance_Bottom
```C
float3 Transmittance_Bottom(float r, float mu, float d) 
{
    float r1 = sqrt(r * r + d * d + 2.0 * r * mu * d);
    float mu1 = (r * mu + d) / r1;
    return min (Transmittance(r, -mu1), 1.0);
}
```

Transmittance use to take into account both sides of the horizon, but now this is split up into separate functions.

Instead of pathLength < maxPathLength I check to see if anything is in-front of the atmosphere.

```c
if (pathLength < (Rg - atmosOffset))
{
    // reduce total in-scattered light when surface hit 
    // within atmosphere
    // fíx described in chapter 5.1.1 
    attenuation = Transmittance_Bottom(startPosHeight, muStartPos, pathLength);
 
    float muEndPos = dot(surfacePos, viewDir) / surfacePosHeight; 
    inscatterSurface = Texture4D(_Inscatter, surfacePosHeight, muEndPos, musEndPos, nuStartPos);

    // Inscatter for objects infront of the sky
    inscatter = max(inscatter - attenuation.rgbr * inscatterSurface, 0.0f) * pathLength/ (Rg  -  fogDensity); 

    irradianceFactor = 1.0f;
} 
```

I then removed all of the code for the if block because we do not need to blend the artifact.
```if (abs(muStartPos - muHorizon) < EPSILON_INSCATTER) ```

## After Changes

![Attenuation_Better_Assume_Unit_Sphere](https://user-images.githubusercontent.com/8560365/104270147-6221b500-545d-11eb-8d46-a82fd19fd5fe.PNG)
After applying the changes to the attenuation calculations we no longer have the strange artifact from division. It looks much better, but is still incorrect, I need to find out how to take the height into consideration when calculating mu (still figuring that out). 

Inscatter will also look better because we are changing the intensity of the fog depending on how close the geometry is to us.

https://user-images.githubusercontent.com/8560365/104270632-8cc03d80-545e-11eb-829d-356822f278a2.mp4

From the ground you can not discern any visual distortions.

https://user-images.githubusercontent.com/8560365/104270636-8fbb2e00-545e-11eb-9f58-777466b2719d.mp4

You can change the fog intensity.

![space](https://user-images.githubusercontent.com/8560365/104271126-b5950280-545f-11eb-81c9-3d2b9b4b5c8d.PNG)

Transitioning to space is intact.

I would like to hear your thoughts on this.

**Comment by simeonradivoev** [comment]
I remember something about this issue, and it is caused because the precomputed texture is for a perfect sphere. You can get away with blending some of it when you have a huge planet but it doesn't work if your mountains are super huge or your planet is small.
Not sure what you can do, except tricks as you did to minimize it. Or maybe investigate how others have solved it.
