### ISSUE TITLE
VR Support

### ISSUE THREAD

**Issue by AustinSmith13** [simeonradivoev/GPU-Planetary-Rendering#4]
Hello, I'm looking into adding VR Support. I've read unity docs [here](https://docs.unity3d.com/Manual/SinglePassInstancing.html) on single pass instanced and it seems like this is bugged for the deferred rendering pipeline. Multi Pass seems to work, but I'm not sure how I should be calculating the offset for this. Currently it is doubling, I see two suns because they do not align properly on each eye. 

I've tried using UnityStereoScreenSpaceUVAdjust but this returns my UV coord unmodified. I'm guessing its only for single pass stereo rendering. Now I'm looking into grabbing the left and right cameras and injecting the offset/scale manually into the ComputeBuffer although I'm not completely sure how to calculate this. Do you know how to set this up for VR?

I'll post my solution if I find one.

**Comment by AustinSmith13** [comment]
I have a solution, I'll share it incase someone else is having this issue.

In AtmosphericScatter.cs Add 4 global matrix vars for left and right eyes (WorldFromView and ViewFromScreen).
```C#
  if (this.camera.stereoEnabled)
            {
                // Both stereo eye inverse view matrices
                Matrix4x4 leftWorldFromView = this.camera.GetStereoViewMatrix(Camera.StereoscopicEye.Left).inverse;
                Matrix4x4 rightWorldFromView = this.camera.GetStereoViewMatrix(Camera.StereoscopicEye.Right).inverse;

                // Both stereo eye inverse projection matrices, plumbed through GetGPUProjectionMatrix to compensate for render texture
                Matrix4x4 left_screen_from_view = this.camera.GetStereoProjectionMatrix(Camera.StereoscopicEye.Left);
                Matrix4x4 right_screen_from_view = this.camera.GetStereoProjectionMatrix(Camera.StereoscopicEye.Right);
                Matrix4x4 leftViewFromScreen = GL.GetGPUProjectionMatrix(left_screen_from_view, true).inverse;
                Matrix4x4 rightViewFromScreen = GL.GetGPUProjectionMatrix(right_screen_from_view, true).inverse;

                // Negate [1,1] to reflect Unity's CBuffer state
                leftViewFromScreen[1, 1] *= -1;
                rightViewFromScreen[1, 1] *= -1;

                lightingBuffer.SetGlobalMatrix("_LeftWorldFromView", leftWorldFromView);
                lightingBuffer.SetGlobalMatrix("_RightWorldFromView", rightWorldFromView);
                lightingBuffer.SetGlobalMatrix("_LeftViewFromScreen", leftViewFromScreen);
                lightingBuffer.SetGlobalMatrix("_RightViewFromScreen", rightViewFromScreen);
            } else
```

Here is the modified shader "AtmosphericScatter.shader"

```glsl
Shader "Sky/AtmosphereImageEffect"
{
	Properties 
	{
		_MainTex("Base (RGB)", any) = "white" {}
		_Test("Test", Vector) = (0, 0, 0, 0)
	}
	SubShader 
	{
	    Pass 
	    {
			Blend SrcAlpha OneMinusSrcAlpha
	    	ZTest Off Cull Off ZWrite Off Fog { Mode Off }

			CGPROGRAM
			#pragma vertex vert
			#pragma fragment frag
			#include "UnityCG.cginc"
			#pragma target 5.0
			#include "Atmosphere.cginc"
			
			sampler2D _MainTex;
			
			struct appdata { 
				float4 vertex : POSITION;
				float3 texcoord : TEXCOORD0;

			};


			struct v2f 
			{
				float4 pos : SV_POSITION;
				float2 uv : TEXCOORD0;
			};
			
			v2f vert (appdata v)
			{
			    v2f o;

				o.pos = v.vertex * float4(2,2,1,1) + float4(-1,-1,0,0);
				o.uv = v.texcoord;
				o.uv.y = 1.0 - o.uv.y;

			    return o;
			}

			float3 _Test;
			
			sampler2D _CameraDepthTexture;
			sampler2D _CameraDepthNormalsTexture;
			float4x4 _ViewProjectInverse;
			float4x4 _CameraInv;
			float4x4 _ViewMatrix;
			float4 _CamScreenDir;
			float4 _LightDir;
			float4 _LightColor;
			float4x4 unity_WorldToLight;
			float _FarPlane;

			float4x4 _LeftWorldFromView;
			float4x4 _RightWorldFromView;
			float4x4 _LeftViewFromScreen;
			float4x4 _RightViewFromScreen;

			half4 frag (v2f i) : COLOR
			{	
				float2 screenUV = UnityStereoTransformScreenSpaceTex(i.uv);
				float depth = SAMPLE_DEPTH_TEXTURE(_CameraDepthTexture, screenUV);
				
				float4 normal = tex2D (_CameraDepthNormalsTexture, screenUV);

				float4x4 proj, eyeToWorld;

				// Left
				if (unity_StereoEyeIndex == 0) 
				{
					proj = _LeftViewFromScreen;
					eyeToWorld = _LeftWorldFromView;
				}
				// Right
				else 
				{
					proj = _RightViewFromScreen;
					eyeToWorld = _RightWorldFromView;
				}

				float2 uvClip = i.uv * 2.0 - 1.0;
				float4 clipPos = float4(uvClip, depth, 1.0);

				float4 vpos = mul(proj, clipPos);
				vpos /= vpos.w;
				float3 wpos = mul(eyeToWorld, vpos).xyz - EARTH_POS;

				float4 surfaceColor = UNITY_SAMPLE_SCREENSPACE_TEXTURE(_MainTex, screenUV);
			    float3 viewDir = normalize(EARTH_POS + wpos - _WorldSpaceCameraPos.xyz);

				float3 attenuation = float3(0, 0, 0);
				float irradianceFactor = 0;


				float3 inscat = GetInscatteredLight(depth, wpos, vpos, screenUV, viewDir, attenuation, irradianceFactor);
				float3 reflected = GetReflectedLight(wpos, depth, attenuation, irradianceFactor, normal, surfaceColor);

			    return float4(inscat + reflected, 1);
			}
			ENDCG
	    }
	}
}
```

There are other modifications in this, but the important part is calculating wpos correctly with the left and right eyeToWorld matrix.


Resources:
https://github.com/Unity-Technologies/Graphics/blob/master/com.unity.postprocessing/PostProcessing/Runtime/PostProcessLayer.cs
https://docs.unity3d.com/Manual/SinglePassStereoRendering.html
https://forum.unity.com/threads/get-left-right-cameras-textures-offsets.517504/
https://docs.unity3d.com/ScriptReference/Camera.GetStereoViewMatrix.html

**Comment by AustinSmith13** [comment]
The last puzzle piece to this is figuring out why single pass stereo instanced rendering wont work with the deferred rendering pipeline if anyone has info on this I would love to know.

**Comment by simeonradivoev** [comment]
Could be related to the old Unity version.  Btw I think you can just use an array for the matrices, that's what unity does if I am not mistaken.

**Comment by AustinSmith13** [comment]
``Could be related to the old Unity version.``

I'm currently on ``Unity 2019.4.16`` using their new XR Management Plugin. They only support multi-pass and single pass instancing. Single Pass seems to be broken with the post processing stack v2 so diving into their code base didn't help me find any answers to this issue.

I've posted the question on unity forums here.
https://forum.unity.com/threads/custom-screen-effect-left-eye-gray-when-using-single-pass-instancing-spi-deferred-rendering.1040530/

I haven't tested if this issue affects your projects unity version, but it probably does because SPI requires some special handling both in the shader and renderer.

``Btw I think you can just use an array for the matrices, that's what unity does if I am not mistaken.``
Are there any benefits to using an array over passing them as separate variables?

**Comment by simeonradivoev** [comment]
`Are there any benefits to using an array over passing them as separate variables?`
Except being cleaner I don't think so. The branching statement when choosing the matrix is probably optimized by the compiler.

Yea I've had lots of issues with the single-pass rendering in 2019. Not sure if moving it to one of the rendering pipelines would be beneficial.

**Comment by AustinSmith13** [comment]
When I get a chance this weekend I'll take a look at HDRP and see if I have better luck.

**Comment by AustinSmith13** [comment]
I'm going to close this, I've got it working for my needs.

**Comment by adellari** [comment]
Hi @AustinSmith13 I'm working on the VR implementation for this project, thank you so much for a great thread! I have implemented your adjustments, but somehow still appear to be getting some rendering inconsistencies that I think are coming from depth discrepancies between the left and right eyes. Would you mind sharing Atmosphere.cginc or how you modified the getReflectedLight method?

**Comment by AustinSmith13** [comment]
Hi @adellari, when I get back from vacation I'll post the files.
