### ISSUE TITLE
Physics not working in Unity 2021?

### ISSUE THREAD

**Issue by dev-bre** [simeonradivoev/GPU-Planetary-Rendering#5]
Hi,
When I add an object with a RigidBody, the object keeps going through the planet mesh. 
I noticed that if I disable and then re-enable the mesh collider on the chunck of the planet mesh from the Unity editor instead, the physics works again.

Looks like the mesh collider bounds need to be recalculated somewhere. 

Any suggestion? 

I am using Unity 2021.3.3f1

**Comment by simeonradivoev** [comment]
Maybe [this](https://docs.unity3d.com/ScriptReference/Mesh.RecalculateBounds.html) will work. Or could just be [this](https://docs.unity3d.com/ScriptReference/Physics.SyncTransforms.html).

**Comment by dev-bre** [comment]
I will try that thanks. I fixed it resetting the mesh on the mesh filter in the recalculate vertices method.

I have a related question, I noticed that collisions get disabled when the camera moves away from a chunk to go to another, this is good in general, but If you have an object on that chunk, when the mesh collider gets disabled, the object will start falling through the mesh.

Do you think would be difficult to implement a way to keep the mesh collider on if an object is detected?

**Comment by simeonradivoev** [comment]
This is an optimization I think, probably better to just make the object sleep.

**Comment by dev-bre** [comment]
Thanks for clarifying.
