### ISSUE TITLE
How to define the sea level?

### ISSUE THREAD

**Issue by dev-bre** [simeonradivoev/GPU-Planetary-Rendering#6]
Hi, this project is really cool, I was wondering if there is a specific noise configuration to define a sea level for the generated world?

At the moment it gets generated like a massive land with mountains, but is there a way to have flat zones which would translate in water?

**Comment by simeonradivoev** [comment]
Should be easy with a clamp, but no currently there isn't a way.

**Comment by dev-bre** [comment]
Can you be a bit more specific? Even a pointer to where I should make the change would be helpful. 
I would assume it is a change to be made in the surface shader, any suggestions?

**Comment by simeonradivoev** [comment]
Yes, the noise function will just have to be modified, if I remember correctly `PlanetSurfaceComputeShader.compute` needs to be changed.

**Comment by dev-bre** [comment]
Thanks.
I was hoping in some advice about how to make the change.

For instance, willing to generate a planet with same flat areas, do you have any suggestion on how to do it?

**Comment by simeonradivoev** [comment]
Use a value of another noise as the lerp between the original lerp and a flat number or you can straight up do a max(0.1, noise), which would make all areas below 0.1 height be 0.1 and appear flat.

**Comment by dev-bre** [comment]
Thanks, I would assume this should be done in the vert() function of the shader?

**Comment by dev-bre** [comment]
Apologies for opening this issue again, any chance you could point me to where I should make the change?

Here it is an extract of the compute shader you mentioned:

```
float3 vertex = vertexBuffer[id.x];
float3 Pos = vertex + normalize(vertex) * (1 - turbulence(vertex,4)) * TerrainScale;
...
vertexBuffer[id.x] = Pos;
```
I tried a couple of things, but none of them are really giving me any control on the surface as I would.

In order to have some flat areas, what should I add to the Pos vector?

**Comment by simeonradivoev** [comment]
Make a new cginclude file `NoiseHelper.cginc`

add to it:
```
#include "ImprovedPerlinNoise3D.cginc"

inline float noise(float3 p,int o)
{
    return (1 - min(turbulence(p,o),0.5));
}
```

then include it in both `PlanetSurface.shader` and 'PlanetSurfaceComputeShader.compute' in place of the 
`#include "ImprovedPerlinNoise3D.cginc"`

then just use the noise function in both. I forgot the `PlanetSurface.shader` also calculates the normals per pixel so it's detailed no matter the mesh complexity.

![image](https://user-images.githubusercontent.com/9950198/190504271-4db0f2a2-2f68-4e6c-b303-553c644efca6.png)

**Comment by dev-bre** [comment]
this is great thanks a lot this helps understanding how the noise works in this proj.
