### ISSUE TITLE
Elevation based mesh colors

### ISSUE THREAD

**Issue by dev-bre** [simeonradivoev/GPU-Planetary-Rendering#7]
Hi,
I am trying to give the planet different colours to the mesh based on the elevation.

For instance:
Blue->green->light brown -> dark brown -> white

Can you suggest how I could achieve this in your code?

I see there is a terrainHeight property in the surface shader, but doesn't look like it used.

I would assume what is needed to do is something like:

1. Calculate the min and max elevation of the planet while it gets generated
2. Define a gradient which maps the minMax range.
3. Evaluate the color of the current vertex based on its elevation against the gradient

Do you have any suggestion on how to achieve this? Quite new to shaders, so any suggestion/guidance on how to implement this in your code would be appreciated.

The first issue would be how to know Min and max elevation of the planet and how to know the elevation of the single vertex.

**Comment by dev-bre** [comment]
Any suggestion about how to takle any of these points?

**Comment by simeonradivoev** [comment]
You have to do it in `SurfaceShader.shader` should be easy to map the colors based on the noise value that ranges from 0 to 1.
